define([], function() {
  return {
    "PropertyPaneDescription": "Configure the Tech Elixir Solution Center web part.",
    "GeneralGroupName": "General",
    "DataGroupName": "Data Source",
    "ListNamesGroupName": "SharePoint List Names",
    "DisplayGroupName": "Display Settings",
    "WebPartTitleFieldLabel": "Web Part Title",
    "UseMockDataFieldLabel": "Use Mock Data",
    "SolutionRegistryListNameFieldLabel": "Solution Registry List",
    "SolutionRegistryListNameFieldDescription": "SharePoint list containing solution records.",
    "DocumentsListNameFieldLabel": "Documents List",
    "DocumentsListNameFieldDescription": "SharePoint list containing solution documents.",
    "ReleasesListNameFieldLabel": "Releases List",
    "ReleasesListNameFieldDescription": "SharePoint list containing release notes.",
    "TechnicalDebtListNameFieldLabel": "Technical Debt List",
    "TechnicalDebtListNameFieldDescription": "SharePoint list containing technical debt items.",
    "ArchitectureAssetsListNameFieldLabel": "Architecture Assets List",
    "ArchitectureAssetsListNameFieldDescription": "SharePoint list containing architecture assets.",
    "IntegrationsListNameFieldLabel": "Integrations List",
    "IntegrationsListNameFieldDescription": "SharePoint list containing integration records.",
    "AccessibilityChecksListNameFieldLabel": "Accessibility Checks List",
    "AccessibilityChecksListNameFieldDescription": "SharePoint list containing accessibility check records.",
    "DefaultSelectedSolutionFieldLabel": "Default Selected Solution",
    "DefaultSelectedSolutionFieldPlaceholder": "Leave empty to show all solutions",
    "ShowGitHubLinksFieldLabel": "Show GitHub Links",
    "ShowPowerPlatformLinksFieldLabel": "Show Power Platform Links",
    "ShowAccessibilityDashboardFieldLabel": "Show Accessibility Dashboard",
    "CompactModeFieldLabel": "Compact Mode",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook"
  }
});
